repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.17.0
    hooks:
      - id: eslint
        additional_dependencies:
          # Manually mirror dev dependencies related to eslint here
          - babel-eslint@10.1.0
          - eslint@7.8.1
          - eslint-config-airbnb@18.2.0
          - eslint-config-prettier@6.11.0
          - eslint-config-wesbos@1.0.1
          - eslint-plugin-html@6.1.0
          - eslint-plugin-import@2.22.0
          - eslint-plugin-jsx-a11y@6.3.1
          - eslint-plugin-prettier@3.1.4
          - eslint-plugin-react@7.20.6
          - eslint-plugin-react-hooks@4.1.2
          - prettier@2.1.1

  - repo: https://github.com/prettier/prettier
    rev: 2.1.1
    hooks:
      - id: prettier
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"
